// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRE1XrfWA5mdvhRAysbWrzM-YKNN1jcew',
    appId: '1:446456504772:web:d1c3aec2926244c6e64491',
    messagingSenderId: '446456504772',
    projectId: 'fluerkkk',
    authDomain: 'fluerkkk.firebaseapp.com',
    storageBucket: 'fluerkkk.firebasestorage.app',
    measurementId: 'G-CRKLP4M84M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMe3fxKnX6gjawVydS6ZMMcY3xx1lbK4',
    appId: '1:446456504772:android:255b5f0021c486fee64491',
    messagingSenderId: '446456504772',
    projectId: 'fluerkkk',
    storageBucket: 'fluerkkk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBilBG6LYYLoe7J-LPGxHhdPcLn_ETlq-8',
    appId: '1:446456504772:ios:cd12e1b3d16a8ea4e64491',
    messagingSenderId: '446456504772',
    projectId: 'fluerkkk',
    storageBucket: 'fluerkkk.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBilBG6LYYLoe7J-LPGxHhdPcLn_ETlq-8',
    appId: '1:446456504772:ios:cd12e1b3d16a8ea4e64491',
    messagingSenderId: '446456504772',
    projectId: 'fluerkkk',
    storageBucket: 'fluerkkk.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRE1XrfWA5mdvhRAysbWrzM-YKNN1jcew',
    appId: '1:446456504772:web:86c2ff1e452f86bfe64491',
    messagingSenderId: '446456504772',
    projectId: 'fluerkkk',
    authDomain: 'fluerkkk.firebaseapp.com',
    storageBucket: 'fluerkkk.firebasestorage.app',
    measurementId: 'G-XR629WWSPD',
  );
}
